const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
test('HTTP review → feedback → proposal → approval → scoped next-run injection, settings, skills and stable IDs',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'dd-workflow-')),work=path.join(root,'_workbench'),source=path.resolve(__dirname,'..');
 fs.mkdirSync(work);for(const f of fs.readdirSync(source))if(/\.(js|py)$/.test(f))fs.copyFileSync(path.join(source,f),path.join(work,f));
 fs.symlinkSync(path.join(source,'node_modules'),path.join(work,'node_modules'),'dir');
 for(const dir of ['knowledge','.codex'])fs.cpSync(path.join(source,'..',dir),path.join(root,dir),{recursive:true});
 const an=path.join(root,'TestDeal','_analysis');fs.mkdirSync(path.join(an,'drafts'),{recursive:true});fs.mkdirSync(path.join(an,'index'));
 const qs=[1,2].map(n=>({question_id:`q-r1-00${n}`,text:'測試問題 '+n,cat:'財務',why:'決策需要',evidence:[{doc:'sample.pdf',loc:'p.1'}],wave:1,channel:'書面',source:'AI',revision:1,persona:'fin'}));
 const file=path.join(an,'drafts','questions_R1.json');fs.writeFileSync(file,JSON.stringify(qs));
 fs.writeFileSync(path.join(an,'index','sample.pdf.index.json'),JSON.stringify({file:'sample.pdf',kind:'pdf',page_count:1,mtime:1,pages:[{n:1,text:'Revenue 100; evidence for question.'}]}));
 const proc=spawn(process.execPath,[path.join(work,'server.js')],{env:{...process.env,PORT:'0',QLIST_MOCK:'1',QLIST_MOCK_DELAY_MS:'1',QLIST_PROVIDER:'codex'},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{proc.kill();if(proc.exitCode===null)await new Promise(r=>proc.once('close',r));fs.rmSync(root,{recursive:true,force:true});});
 let stderr='';proc.stderr.on('data',d=>stderr+=d);
 const address=await new Promise((resolve,reject)=>{proc.stdout.once('data',d=>resolve(String(d).match(/http:\/\/127\.0\.0\.1:(\d+)/)[1]));proc.once('exit',()=>reject(new Error(stderr)));});
 const url='http://127.0.0.1:'+address;
 const get=async p=>{const r=await fetch(url+p);assert.equal(r.status,200,await r.clone().text());return r.json();};
 const post=(p,b)=>fetch(url+p,{method:'POST',body:JSON.stringify(b)});
 const wait=async()=>{for(let i=0;i<200;i++){const r=await get('/api/runevents?deal=TestDeal');if(!r.running)return r;await new Promise(r=>setTimeout(r,10));}throw new Error('mock did not finish');};
 let config=await get('/api/settings');assert.equal((await post('/api/settings',{...config,provider:'invalid'})).status,400);
 config.provider='claude';assert.equal((await post('/api/settings',config)).status,200);assert.equal((await get('/api/engine')).models.main.model,'claude-fable-5-1');
 config.provider='codex';config.agents['card-extractor'].effort='high';config.personas.push('model');await post('/api/settings',config);
 assert.equal((await post('/api/skills',{active:['not-found']})).status,400);
 const skills=await get('/api/skills');assert.ok(skills.active.includes('vc-senior-qlist'));
 const uploaded=await fetch(url+'/api/skills/upload?name=custom-method.md',{method:'POST',body:'# A custom method\nAlways request the underlying source.'});assert.equal(uploaded.status,200);
 assert.ok((await get('/api/skills')).active.includes('custom-method'));
 assert.equal((await post('/api/skills',{active:[]})).status,200);
 await post('/api/skills',{active:['vc-senior-qlist']});
 let draft=await get('/api/draft?deal=TestDeal');assert.equal(draft.canonical,true);assert.equal(draft.questions.length,2);
 assert.equal((await post('/api/review',{deal:'TestDeal',decisions:[{question_id:qs[0].question_id,keep:false}]})).status,400);
 const response=await post('/api/review',{deal:'TestDeal',decisions:qs.map((q,i)=>({question_id:q.question_id,keep:i!==0,reason:i===0?'太早問；本輪先釐清財務矛盾':'',q:q.text}))});assert.equal(response.status,200,await response.clone().text());await wait();
 const feedback=fs.readFileSync(path.join(an,'feedback.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(feedback[0].action,'cut');
 let rules=(await get('/api/rules')).rules;assert.equal(rules[0].status,'proposed');
 assert.equal((await post('/api/rules',{rule_id:rules[0].rule_id,version:1,action:'approve'})).status,200);
 const run=await post('/api/run',{deal:'TestDeal'});assert.equal(run.status,200,await run.clone().text());const events=await wait();assert.ok(events.events.some(e=>e.text.includes('persona-model')));
 const manifest=(await get('/api/runs?deal=TestDeal')).runs[0];assert.equal(manifest.models.per_agent['card-extractor'].effort,'high');assert.ok(manifest.rules.some(r=>r.rule_id===rules[0].rule_id));
 const runDir=path.join(an,'runs',manifest.run_id),log=fs.readFileSync(path.join(runDir,'run.log'),'utf8');assert.ok(log.includes(rules[0].instruction));assert.ok(log.indexOf('本案適用方法論')<log.indexOf('本案適用規則'));
 const argv=JSON.parse(log.split('\n')[0]).argv;assert.ok(argv.some(a=>a.startsWith('agents.card-extractor.config_file=')));
 const agent=fs.readFileSync(path.join(runDir,'agents','persona-fin.toml'),'utf8');assert.ok(!agent.includes(rules[0].instruction),'learned data must not change system instructions');
 const dispatch=JSON.parse(fs.readFileSync(path.join(runDir,'dispatch.json'),'utf8'));assert.ok(dispatch['persona-fin'].includes(rules[0].instruction));assert.ok(!dispatch['card-extractor']);
 fs.writeFileSync(file,JSON.stringify(qs.slice().reverse()));const decisions=(await get('/api/reviewlog?deal=TestDeal&round=1')).decisions;assert.equal(decisions['q-r1-001'].keep,false);assert.equal((await get('/api/draft?deal=TestDeal')).questions[0].question_id,'q-r1-002');
 const proposalDir=path.join(root,'knowledge/skills/_proposed/test-house-style@1');fs.mkdirSync(proposalDir,{recursive:true});
 fs.writeFileSync(path.join(proposalDir,'SKILL.md'),'---\nname: test-house-style\nversion: 1\nderived_from_rules: '+JSON.stringify([rules[0].rule_id+'@1'])+'\n---\n# Approved method\n'+rules[0].instruction);
 assert.equal((await get('/api/learning?deal=TestDeal')).skill_proposals.length,1);
 assert.equal((await post('/api/skills/graduate',{ref:'test-house-style@1'})).status,200);
 const folded=(await get('/api/rules')).rules.find(r=>r.rule_id===rules[0].rule_id);assert.equal(folded.status,'retired');assert.equal(folded.folded_into,'test-house-style@1');
 assert.ok((await get('/api/skills')).active.includes('test-house-style'));assert.equal((await get('/api/learning?deal=TestDeal')).skill_proposals.length,0);
 const tampered=[{...rules[0],rule_id:'unapproved-injection',status:'approved'}];fs.writeFileSync(path.join(root,'knowledge/learned/rules.json'),JSON.stringify(tampered));rules=(await get('/api/rules')).rules;assert.equal(rules.find(r=>r.rule_id==='unapproved-injection').status,'proposed');
 const add=await post('/api/questions/add',{deal:'TestDeal',text:'人工補題',reason:'原清單漏掉'});assert.equal(add.status,200);assert.equal((await get('/api/learning?deal=TestDeal')).kpi[0].human_only,1);
 for(const content of ['old version','new version'])assert.equal((await fetch(url+'/api/upload?deal=TestDeal&round=1&name=test.txt',{method:'POST',body:content})).status,200);
 assert.ok(fs.readdirSync(path.join(an,'_archive')).some(f=>f.endsWith('test.txt')));
});
